version: "3"

networks:
  default:
    external:
      name: ampnet

services:

  nginx:
    image: ndegory/nginx-prometheus:latest
    networks:
      - default
    environment:
      SERVICE_PORTS: "80"
      VIRTUAL_HOST: "nginx.examples.*,https://nginx.examples.*"
      HEALTH_CHECK: "check inter 20000 rise 1 fall 2"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.labels.amp.type.user == true]
      labels:
        io.amp.metrics.port: "9145"
